/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SetLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("dk/sdu/mmmi/mdsd/ex/parser/antlr/internal/InternalSetLang.tokens");
	}
}
