/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex.parser.antlr;

import com.google.inject.Inject;
import dk.sdu.mmmi.mdsd.ex.parser.antlr.internal.InternalSetLangParser;
import dk.sdu.mmmi.mdsd.ex.services.SetLangGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SetLangParser extends AbstractAntlrParser {

	@Inject
	private SetLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSetLangParser createParser(XtextTokenStream stream) {
		return new InternalSetLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public SetLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SetLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
