/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.ex.SetLangRuntimeModule;
import dk.sdu.mmmi.mdsd.ex.SetLangStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SetLangIdeSetup extends SetLangStandaloneSetup {
  @Override
  public Injector createInjector() {
    SetLangRuntimeModule _setLangRuntimeModule = new SetLangRuntimeModule();
    SetLangIdeModule _setLangIdeModule = new SetLangIdeModule();
    return Guice.createInjector(Modules2.mixin(_setLangRuntimeModule, _setLangIdeModule));
  }
}
