/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SetLangIdeModule extends AbstractSetLangIdeModule {
}
