/* generated by SetLang parser */

package setdsl;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import utils.*;

public class XP1HelloWorld extends AbstractRecordProgram {
		
	private External external;
	
	public XP1HelloWorld(External external) {
		this.external = external;
	}
	
	public List compute() {
		List results = new ArrayList();
		results.add(new r3(5,5,Set.of(5),Set.of(5, 5)).z);
		results.add(set_projection(new r3(6,6,Set.of(6),Set.of(6, 6, 6)).y, 1));
		results.add(set_filter(new r3(7,7,Set.of(7),Set.of(7, 7, 7, 7)).x, external::mod3));
		return results;
	}
	
	public class r1 {
		private int a;
		public Set x;
		
		public r1(int a) {
			this.a = a;
			this.x = Set.of(this.a);
		}
	}
	
	public class r2 extends r1 {
		private int b;
		private Set c;
		public Set y;
		
		public r2(int a, int b, Set c) {
			super(a);
			this.b = b;
			this.c = c;
			this.y = set_union(this.x, set_product(Set.of(this.b), this.c));
		}
	}
	
	public class r3 extends r2 {
		private Set d;
		public Set z;
		
		public r3(int a, int b, Set c, Set d) {
			super(a, b, c);
			this.d = d;
			this.z = set_union(set_intersection(this.x, this.y), Set.of(this.d));
		}
	}
	
	public interface External {
		public boolean mod3(Set a);
	}
}
