/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SetLangStandaloneSetup extends SetLangStandaloneSetupGenerated {
  public static void doSetup() {
    new SetLangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
