/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex;

import com.google.inject.Binder;
import dk.sdu.mmmi.mdsd.ex.scoping.SetLangScopeProvider;
import org.eclipse.xtext.scoping.IScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SetLangRuntimeModule extends AbstractSetLangRuntimeModule {
  @Override
  public void configure(final Binder binder) {
    super.configure(binder);
    binder.<IScopeProvider>bind(IScopeProvider.class).to(SetLangScopeProvider.class);
  }
}
