/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractSetLangValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(dk.sdu.mmmi.mdsd.ex.setLang.SetLangPackage.eINSTANCE);
		return result;
	}
}
