/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex.ui;

import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.examen.ui.internal.ExamenActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SetLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ExamenActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ExamenActivator activator = ExamenActivator.getInstance();
		return activator != null ? activator.getInjector(ExamenActivator.DK_SDU_MMMI_MDSD_EX_SETLANG) : null;
	}

}
