/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex.setLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.ex.setLang.Program#getName <em>Name</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.ex.setLang.Program#getExternalDefs <em>External Defs</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.ex.setLang.Program#getRecords <em>Records</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.ex.setLang.Program#getComputes <em>Computes</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.ex.setLang.SetLangPackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see dk.sdu.mmmi.mdsd.ex.setLang.SetLangPackage#getProgram_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.ex.setLang.Program#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>External Defs</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.ex.setLang.ExternalDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>External Defs</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.ex.setLang.SetLangPackage#getProgram_ExternalDefs()
   * @model containment="true"
   * @generated
   */
  EList<ExternalDef> getExternalDefs();

  /**
   * Returns the value of the '<em><b>Records</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.ex.setLang.Record}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Records</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.ex.setLang.SetLangPackage#getProgram_Records()
   * @model containment="true"
   * @generated
   */
  EList<dk.sdu.mmmi.mdsd.ex.setLang.Record> getRecords();

  /**
   * Returns the value of the '<em><b>Computes</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.ex.setLang.Compute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Computes</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.ex.setLang.SetLangPackage#getProgram_Computes()
   * @model containment="true"
   * @generated
   */
  EList<Compute> getComputes();

} // Program
