/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex.setLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Projection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.ex.setLang.Projection#getOp <em>Op</em>}</li>
 *   <li>{@link dk.sdu.mmmi.mdsd.ex.setLang.Projection#getIndices <em>Indices</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.ex.setLang.SetLangPackage#getProjection()
 * @model
 * @generated
 */
public interface Projection extends Expression
{
  /**
   * Returns the value of the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' containment reference.
   * @see #setOp(Expression)
   * @see dk.sdu.mmmi.mdsd.ex.setLang.SetLangPackage#getProjection_Op()
   * @model containment="true"
   * @generated
   */
  Expression getOp();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.mdsd.ex.setLang.Projection#getOp <em>Op</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' containment reference.
   * @see #getOp()
   * @generated
   */
  void setOp(Expression value);

  /**
   * Returns the value of the '<em><b>Indices</b></em>' attribute list.
   * The list contents are of type {@link java.lang.Integer}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Indices</em>' attribute list.
   * @see dk.sdu.mmmi.mdsd.ex.setLang.SetLangPackage#getProjection_Indices()
   * @model unique="false"
   * @generated
   */
  EList<Integer> getIndices();

} // Projection
