/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex.setLang;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.mdsd.ex.setLang.Set#getValues <em>Values</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.mdsd.ex.setLang.SetLangPackage#getSet()
 * @model
 * @generated
 */
public interface Set extends Expression
{
  /**
   * Returns the value of the '<em><b>Values</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mmmi.mdsd.ex.setLang.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Values</em>' containment reference list.
   * @see dk.sdu.mmmi.mdsd.ex.setLang.SetLangPackage#getSet_Values()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getValues();

} // Set
