/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex.ui.tests;

import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.examen.ui.internal.ExamenActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SetLangUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ExamenActivator.getInstance().getInjector("dk.sdu.mmmi.mdsd.ex.SetLang");
	}

}
