/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SetLangStandaloneSetup extends SetLangStandaloneSetupGenerated {

	def static void doSetup() {
		new SetLangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
