/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex.serializer;

import com.google.inject.Inject;
import dk.sdu.mmmi.mdsd.ex.services.SetLangGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class SetLangSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SetLangGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Tuple_CommaKeyword_3_0_a;
	protected AbstractElementAlias match_Tuple_CommaKeyword_3_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SetLangGrammarAccess) access;
		match_Tuple_CommaKeyword_3_0_a = new TokenAlias(true, true, grammarAccess.getTupleAccess().getCommaKeyword_3_0());
		match_Tuple_CommaKeyword_3_0_p = new TokenAlias(true, false, grammarAccess.getTupleAccess().getCommaKeyword_3_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Tuple_CommaKeyword_3_0_a.equals(syntax))
				emit_Tuple_CommaKeyword_3_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Tuple_CommaKeyword_3_0_p.equals(syntax))
				emit_Tuple_CommaKeyword_3_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','*
	 *
	 * This ambiguous syntax occurs at:
	 *     values+=UnionIntersection (ambiguity) ']' '#' (rule end)
	 *     values+=UnionIntersection (ambiguity) ']' (rule end)
	 *     values+=UnionIntersection (ambiguity) values+=UnionIntersection
	 
	 * </pre>
	 */
	protected void emit_Tuple_CommaKeyword_3_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ','+
	 *
	 * This ambiguous syntax occurs at:
	 *     values+=UnionIntersection (ambiguity) values+=UnionIntersection
	 
	 * </pre>
	 */
	protected void emit_Tuple_CommaKeyword_3_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
