/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.validation

import org.eclipse.xtext.validation.Check
import dk.sdu.mmmi.mdsd.math.MathExp
import dk.sdu.mmmi.mdsd.math.MathPackage
import dk.sdu.mmmi.mdsd.math.VarBinding

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MathValidator extends AbstractMathValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MathPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	public static final String VAR_UNIQUE = 'var_unique'
	
	@Check
	def void uniqueGlobalVariableDefinition(VarBinding binding){
		if((binding.eContainer as MathExp).exps.filter[name == binding.name].size > 1)
			error("Duplicate global variable", MathPackage.eINSTANCE.varBinding_Name, VAR_UNIQUE)
	}
	
}
