/*
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import dk.sdu.mmmi.mdsd.ide.contentassist.antlr.internal.InternalMathParser;
import dk.sdu.mmmi.mdsd.services.MathGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MathParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MathGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MathGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSumDiffAccess().getAlternatives_1_0(), "rule__SumDiff__Alternatives_1_0");
			builder.put(grammarAccess.getProdQuotAccess().getAlternatives_1_0(), "rule__ProdQuot__Alternatives_1_0");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getExpAccess().getGroup(), "rule__Exp__Group__0");
			builder.put(grammarAccess.getSumDiffAccess().getGroup(), "rule__SumDiff__Group__0");
			builder.put(grammarAccess.getSumDiffAccess().getGroup_1(), "rule__SumDiff__Group_1__0");
			builder.put(grammarAccess.getSumDiffAccess().getGroup_1_0_0(), "rule__SumDiff__Group_1_0_0__0");
			builder.put(grammarAccess.getSumDiffAccess().getGroup_1_0_1(), "rule__SumDiff__Group_1_0_1__0");
			builder.put(grammarAccess.getProdQuotAccess().getGroup(), "rule__ProdQuot__Group__0");
			builder.put(grammarAccess.getProdQuotAccess().getGroup_1(), "rule__ProdQuot__Group_1__0");
			builder.put(grammarAccess.getProdQuotAccess().getGroup_1_0_0(), "rule__ProdQuot__Group_1_0_0__0");
			builder.put(grammarAccess.getProdQuotAccess().getGroup_1_0_1(), "rule__ProdQuot__Group_1_0_1__0");
			builder.put(grammarAccess.getParenthesisAccess().getGroup(), "rule__Parenthesis__Group__0");
			builder.put(grammarAccess.getConstantAccess().getGroup(), "rule__Constant__Group__0");
			builder.put(grammarAccess.getVariableUseAccess().getGroup(), "rule__VariableUse__Group__0");
			builder.put(grammarAccess.getVariableBindingAccess().getGroup(), "rule__VariableBinding__Group__0");
			builder.put(grammarAccess.getMathExpAccess().getExpsAssignment(), "rule__MathExp__ExpsAssignment");
			builder.put(grammarAccess.getExpAccess().getNameAssignment_1(), "rule__Exp__NameAssignment_1");
			builder.put(grammarAccess.getExpAccess().getExpAssignment_3(), "rule__Exp__ExpAssignment_3");
			builder.put(grammarAccess.getSumDiffAccess().getRightAssignment_1_1(), "rule__SumDiff__RightAssignment_1_1");
			builder.put(grammarAccess.getProdQuotAccess().getRightAssignment_1_1(), "rule__ProdQuot__RightAssignment_1_1");
			builder.put(grammarAccess.getParenthesisAccess().getExpAssignment_2(), "rule__Parenthesis__ExpAssignment_2");
			builder.put(grammarAccess.getConstantAccess().getValueAssignment_1(), "rule__Constant__ValueAssignment_1");
			builder.put(grammarAccess.getVariableUseAccess().getRefAssignment_1(), "rule__VariableUse__RefAssignment_1");
			builder.put(grammarAccess.getVariableBindingAccess().getIdAssignment_2(), "rule__VariableBinding__IdAssignment_2");
			builder.put(grammarAccess.getVariableBindingAccess().getBindingAssignment_4(), "rule__VariableBinding__BindingAssignment_4");
			builder.put(grammarAccess.getVariableBindingAccess().getBodyAssignment_6(), "rule__VariableBinding__BodyAssignment_6");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MathGrammarAccess grammarAccess;

	@Override
	protected InternalMathParser createParser() {
		InternalMathParser result = new InternalMathParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MathGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
