/**
 * generated by Xtext 2.33.0
 */
package dk.sdu.mmmi.mdsd.ex.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SetLangUiModule extends AbstractSetLangUiModule {
  public SetLangUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
